### PR TITLE
Fixing validation bug

### PR DESCRIPTION
**Pull request by Slowblitz**
fixing #32

### CODE REVIEW

**Comment by SylvainTakerkart** [comment]
Hi! So, I guess I trust you on the fixes!!!

One question: how does this interact with my last question here (https://github.com/INT-NIT/AnDOChecker/issues/13#issuecomment-689440516)?

**Comment by SylvainTakerkart** [comment]
Also, more precisely... I guess this error should have been detected with the unit tests that apply the checker on all the datasets provided, no? Why wasn't it detected? Maybe it means that the unit test should be improved, no?

**Comment by Slowblitz** [comment]
Hello @SylvainTakerkart  ,
Yes we need to update the datasets directory "test"  and improve the unit test at the same time .

**Comment by SylvainTakerkart** [comment]
OK, I'm merging this one, and you can open a different PR to update the unit tests and associated datasets...

**Pull request merged**
