### PR TITLE
New data set and test

### LINKED ISSUE #13: Improving unit tests
Hi,

I'd like to suggest a few things to improve the unit tests:

1. we need to have unit test which do not use the datasets... you need a procedure that directly tests the functions; also, you need to have one test for each type of error!

2. we also need to keep the tests on the datasets! and there, we need to improve the datasets to improve the tests:
- we need one fully valid dataset (maybe several ones with different characteristics)
- we need to construct datasets that deviates from the valid dataset but violate one and only one spec (one dataset for each type of error)
- we need one or several datasets that violate several types of errors

### PR DESCRIPTION
**Pull request by Slowblitz**
New datasets :

- dataset001 = wrong exp name
- dataset002 = wrong sub name
- dataset003 = wrong ses name
- dataset004 = no derivatives folder
- dataset005 = no metadata folder
- dataset006 = no rawdata folder
- dataset007 = good dataset

Updated test to match new datasets fix #13

### CODE REVIEW

**Comment by SylvainTakerkart** [comment]
Hi @Slowblitz ! Overall, everything looks good in what you changed! Thanks ;)

But I found a bug: if you give a non-existing directory as input, the checker tells you it's valid!

~/tmp/AnDOChecker/ando$ python checker.py -v tests/dataset010
tests/dataset010: Is validated by AnDOChecker

~/tmp/AnDOChecker/ando$ python checker.py -v tests/biloute
tests/biloute: Is validated by AnDOChecker

We had decided together that an empty exp-XXX directory is valid. But a non-existing directory should not be validated! Can you correct for this?

**Comment by Slowblitz** [comment]
Found another bug do not  merge yet =)

**Comment by SylvainTakerkart** [comment]
OK, I'm waiting! Let me know!

**Comment by Slowblitz** [comment]
Seems good to me , you can merge =)

**Comment by SylvainTakerkart** [comment]
ok, this seems to work now! ...except that for the different datasets, I don't get what you mentioned above, i.e:

    dataset001 = wrong exp name
    dataset002 = wrong sub name
    dataset003 = wrong ses name
    dataset004 = no derivatives folder
    dataset005 = no metadata folder
    dataset006 = no rawdata folder
    dataset007 = good dataset

what I get is this:


    dataset001 = wrong exp name
    dataset002 = wrong sub name
    dataset003 = wrong ses name
    dataset004 = wrong exp name
    dataset005 = no metadata folder
    dataset006 = wrong ses name
    dataset007 = good dataset

Can you re-check if something has changed since you said this? Or correct the datasets so that they do what you said?

**Comment by Slowblitz** [comment]
Yes seems that I have not commit the good ones, now works as describe above.

**Comment by SylvainTakerkart** [comment]
ok, everything seems ok now! I'm waiting for the travis checks to be finished to merge...

**Comment by Slowblitz** [comment]
Ok , but 1 hour and still in queue seems a bit long actually .WDYT ?

**Comment by SylvainTakerkart** [comment]
yes indeed!
I already saw that happening... travis might just be stuck!
can you do a small commit (with almost nothing in it)? this will reset travis, and hopefully it will go faster...

**Pull request merged**
